name: Life Tracker Backend Test CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Integration tests
        run: NODE_ENV=test npm run test:integration
      - name: Fuzz tests
        run: NODE_ENV=test npm run test:fuzz
      - name: Build Docker image for testing purposes
        run: |
          docker buildx create --use
          docker buildx build --output type=docker --file Dockerfile --platform linux/arm64 .