name: Production Docker Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Integration tests
        run: NODE_ENV=test npm run test:integration
      - name: Unit tests
        run: NODE_ENV=test npm run test:unit
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --platform linux/arm64,linux/amd64 --push --tag ${{ secrets.DOCKER_USERNAME }}/life-tracker-backend:prod .