name: Dev Testing CI/CD

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  test-unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Unit tests
        run: NODE_ENV=test npm run test:unit

  test-lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Lint tests
        run: npm run lint
