name: Fuzz Tests CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      - name: Integration tests
        run: NODE_ENV=test npm run test:integration

  test-fuzz:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Fuzz tests
        run: NODE_ENV=test npm run test:fuzz
